spring.application.name=springfile
# Define que não há limite para um único arquivo
spring.servlet.multipart.max-file-size=-1
# Define que não há limite para a requisição total
spring.servlet.multipart.max-request-size=-1
# Tirar o limite de seguraca do Tomcat
server.tomcat.max-swallow-size=-1
# a partir de 0bytes ele comeca a gravar no disco, evitando estouro de RAM
#spring.servlet.multipart.file-size-threshold=0
# tira o tempo limite da conexao
server.tomcat.connection-timeout=-1